version: "3"
networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=mysqldb
    networks:
      - application
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=5000
  db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - ./data:/var/lib/mysql
  environment:
    MYSQL_USER: arya
    MYSQL_PASSWORD: Arya@123
    MYSQL_DATABASE: qickmate
  networks:
    - application
  container_name: mymysqldb
  healthcheck:
    test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p  || exit 1"]
    interval: 5s
    timeout: 5s
    retries: 5
